---
url: 'git@github.com:iosonoumberto/bgp_mpls_lab_study.git'
devices:
    - ip: '10.102.164.94'
      name: 'r1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.164.88'
      name: 'r3'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.164.85'
      name: 'r4'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.164.71'
      name: 'r5'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.164.7'
      name: 'r6'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.117'
      name: 'r7'
      usr: 'root'
      pass: 'Embe1mpls'

