---
url: 'git@github.com:iosonoumberto/vpn_lab_study.git'
devices:
    - ip: '10.102.244.74'
      name: 'c1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.244.61'
      name: 'pe1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.244.58'
      name: 'pe2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.244.4'
      name: 'p1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.243.119'
      name: 'p2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.241.126'
      name: 'pe3'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.244.16'
      name: 'pe4'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.244.219'
      name: 'c2'
      usr: 'root'
      pass: 'Embe1mpls'

