---
url: 'git@github.com:iosonoumberto/mini_sp.git'
devices:
    - ip: '10.102.162.82'
      name: 'ce1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.67'
      name: 'pe1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.6'
      name: 'pe3'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.53'
      name: 'pe3'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.203'
      name: 'pe4'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.175'
      name: 'p1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.153'
      name: 'p2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.140'
      name: 'ce2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.162.133'
      name: 'ce3'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.161.30'
      name: 'srx'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.161.28'
      name: 'leaf1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.161.226'
      name: 'leaf2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.161.177'
      name: 'spine1'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.161.109'
      name: 'spine2'
      usr: 'root'
      pass: 'Embe1mpls'
    - ip: '10.102.160.97'
      name: 'rr'
      usr: 'root'
      pass: 'Embe1mpls'
